CLS
SCREEN 1
DIM cube(8, 11)
FOR lop = 1 TO 8
        cube(lop, lop + 3) = -1
NEXT
cube(1, 1) = 1
cube(1, 2) = 1
cube(1, 3) = 1
cube(1, 4) = 2
cube(1, 5) = 3
cube(1, 6) = 5
cube(2, 1) = 2
cube(2, 2) = 1
cube(2, 3) = 1
cube(2, 4) = 6
cube(2, 5) = 4
cube(3, 1) = 1
cube(3, 2) = 1
cube(3, 3) = 0
cube(3, 4) = 4
cube(3, 5) = 7
cube(4, 1) = 2
cube(4, 2) = 1
cube(4, 3) = 0
cube(4, 4) = 8
cube(5, 1) = 1
cube(5, 2) = 0
cube(5, 3) = 1
cube(5, 4) = 7
cube(5, 5) = 6
cube(6, 1) = 2
cube(6, 2) = 0
cube(6, 3) = 1
cube(6, 4) = 8
cube(7, 1) = 1
cube(7, 2) = 0
cube(7, 3) = 0
cube(7, 4) = 8
cube(8, 1) = 2
cube(8, 2) = 0
cube(8, 3) = 0





